name: Python 3.11 support
on:
  workflow_dispatch:
  schedule: # UTC at 0200 on Sundays
    - cron: "0 2 * * 0"

env:
  PACKAGE_NAME: 'ansys-geometry-core'
  PACKAGE_NAMESPACE: 'ansys.geometry.core'

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  py311-smoke-tests:
    name: Python 3.11 compatibility
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Build wheelhouse and perform smoke test
        uses: pyansys/actions/build-wheelhouse@main
        with:
          library-name: ${{ env.PACKAGE_NAME }}
          library-namespace: ${{ env.PACKAGE_NAMESPACE }}
          operating-system: ${{ matrix.os }}
          python-version: '3.11'

